"""
GitHub Actions worker — fetches full street address from BRRA EPZEU API.
Runs as one job in a 20-worker matrix.

Usage: python address_worker.py <worker_index> <total_workers> <batch_number>

Input:  missing_addresses_eiks.txt  (generated by generate_missing_addresses.py)
Output: address_results_<worker_idx>.json
        { "EIK": {"street": "...", "post_code": "...", "settlement": "..."} }

Rate limit: ~5 req / 20-25s per IP  →  1 req / 10s is proven safe.
180 EIKs per worker × 20 workers = 3,600 EIKs per batch.
Saves partial results on SIGTERM so no work is lost.
"""

import sys, os, json, time, signal, requests

INTER_REQ_S    = 10     # 1 request every 10s — proven safe rate
MAX_PER_WORKER = 180    # 30 min × 6 req/min = 180 EIKs per worker
REQ_TIMEOUT    = 20
BACKOFF_429    = 30     # seconds to wait after a 429

SEAT_URL = "https://portal.registryagency.bg/CR/api/Deeds/{eik}/Seat"

# Global so SIGTERM handler can access it
results  = {}
out_file = "address_results_0.json"

def save_results():
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False)

def handle_sigterm(signum, frame):
    print(f"\n[SIGTERM] Saving {len(results)} partial results to {out_file}", flush=True)
    save_results()
    sys.exit(0)

signal.signal(signal.SIGTERM, handle_sigterm)

def fetch_address(eik, session):
    """Returns {"street": str, "post_code": str, "settlement": str} or None on hard error."""
    try:
        r = session.get(SEAT_URL.format(eik=eik), timeout=REQ_TIMEOUT)
        if r.status_code == 200:
            data       = r.json()
            addr       = data.get("address", {}) or {}
            settlement = addr.get("settlement", "") or ""
            street     = addr.get("street",     "") or ""
            post_code  = addr.get("postCode",   "") or ""
            return {
                "settlement": settlement.strip(),
                "street":     street.strip(),
                "post_code":  post_code.strip(),
            }
        if r.status_code == 429:
            print(f"  [429] backing off {BACKOFF_429}s", flush=True)
            time.sleep(BACKOFF_429)
            r2 = session.get(SEAT_URL.format(eik=eik), timeout=REQ_TIMEOUT)
            if r2.status_code == 200:
                data       = r2.json()
                addr       = data.get("address", {}) or {}
                settlement = addr.get("settlement", "") or ""
                street     = addr.get("street",     "") or ""
                post_code  = addr.get("postCode",   "") or ""
                return {
                    "settlement": settlement.strip(),
                    "street":     street.strip(),
                    "post_code":  post_code.strip(),
                }
        return {"settlement": "", "street": "", "post_code": ""}
    except Exception as e:
        print(f"  [err] {eik}: {e}", flush=True)
        return None

def main():
    global results, out_file

    if len(sys.argv) != 4:
        print("Usage: python address_worker.py <worker_index> <total_workers> <batch_number>")
        sys.exit(1)

    worker_idx    = int(sys.argv[1])
    total_workers = int(sys.argv[2])
    batch_num     = int(sys.argv[3])
    out_file      = f"address_results_{worker_idx}.json"

    with open("missing_addresses_eiks.txt") as f:
        all_eiks = [line.strip() for line in f if line.strip()]

    per_run    = total_workers * MAX_PER_WORKER
    run_eiks   = all_eiks[:per_run]   # always start from top — file is pruned after each batch

    if not run_eiks:
        print(f"Worker {worker_idx}: nothing to do (batch {batch_num} is empty)")
        save_results()
        return

    worker_eiks = run_eiks[worker_idx::total_workers][:MAX_PER_WORKER]

    print(f"Worker {worker_idx}/{total_workers} | Batch {batch_num} | "
          f"{len(worker_eiks):,} EIKs", flush=True)

    session = requests.Session()
    session.headers.update({"Accept": "application/json", "User-Agent": "Mozilla/5.0"})

    found  = 0   # EIKs that returned a non-empty street
    errors = 0

    for i, eik in enumerate(worker_eiks):
        req_start = time.time()

        data = fetch_address(eik, session)
        if data is None:
            errors += 1
        else:
            results[eik] = data
            if data["street"]:
                found += 1

        if (i + 1) % 50 == 0 or i == len(worker_eiks) - 1:
            print(f"  [{i+1}/{len(worker_eiks)}] streets={found} errors={errors}", flush=True)

        elapsed    = time.time() - req_start
        sleep_time = max(0, INTER_REQ_S - elapsed)
        if sleep_time > 0 and i < len(worker_eiks) - 1:
            time.sleep(sleep_time)

    save_results()
    print(f"\nWorker {worker_idx} done: {found} streets, {errors} errors → {out_file}", flush=True)

if __name__ == "__main__":
    main()
